include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"

errors:
    unused_import: error
    dead_code: warning
    missing_return: error 
    invalid_assignment: error    

linter:
  rules:
    avoid_print
    avoid_final_parameters
    avoid_unnecessary_containers
    avoid_return_types_on_setters
    prefer_const_constructors
    prefer_final_fields
    always_specify_types
    always_put_required_named_parameters_first
    always_declare_return_types
    annotate_overrides
    sort_constructors_first
    sized_box_for_whitespace
    prefer_single_quotes